name: "Automated Tests"
on: [push, pull_request]
jobs:
  jest:
    name: "Jest Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/Jod"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm ci
      - run: pnpm test
